/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you
 * started. For more details on building Java & JVM projects, please refer to
 * https://docs.gradle.org/8.11.1-20241116012204+0000/userguide/building_java_projects.html
 * in the Gradle documentation.
 */

plugins{// Apply the application plugin to add support for building a CLI
        // application in Java.
        application}

repositories{// Use Maven Central for resolving dependencies.
             mavenCentral()}

dependencies{
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)

    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
    implementation("net.java.dev.jna:jna-platform:5.13.0")
    implementation("net.java.dev.jna:jna:5.13.0")
    implementation("com.github.hypfvieh:dbus-java:3.3.1")
    implementation("com.github.hypfvieh:dbus-java-core:3.3.1")
    implementation("org.slf4j:slf4j-simple:2.0.7")

    // This dependency is used by the application.
    implementation(libs.guava)}

// Apply a specific Java toolchain to ease working on different environments.
java {
  toolchain { languageVersion = JavaLanguageVersion.of(23) }
}

application{// Define the main class for the application.
            mainClass = "org.FF.App"}

tasks.named<Test>("test") {
  // Use JUnit Platform for unit tests.
  useJUnitPlatform()
}
